### ISSUE TITLE
Ubuntu fails to boot from source 

### ISSUE THREAD

**Issue by johrstrom** [OSC/ood-ansible#50]
Ubuntu has a few errors in installing due to become permission. But aside from that, once everything is installed and configured, nginx segfaults when the PUN starts to boot.  Here's the error out of journalctl. 

kernel: nginx[20380]: segfault at 18 ip 000055fe8c71c2aa sp 00007fff016eed10 error 4 in nginx-1.17.3[55fe8c5db000+3f9000]

**Comment by johrstrom** [comment]
For posterity, here's the entire stack trace. I tracked it down to the fact that there was a `# commented string` in the locations.ini file.

```text
#0  0x000055f0b628f43e in std::_Rb_tree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::_Select1st<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >::_M_begin() const ()
#1  0x000055f0b628e4cb in std::_Rb_tree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::_Select1st<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >::find(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const ()
#2  0x000055f0b628d319 in std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >::find(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const ()
#3  0x000055f0b6286956 in Passenger::IniFileSection::hasKey(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const ()
#4  0x000055f0b628880c in Passenger::ResourceLocator::getOption(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, boost::shared_ptr<Passenger::IniFileSection> const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
#5  0x000055f0b6288c85 in Passenger::ResourceLocator::ResourceLocator(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
#6  0x000055f0b628b7d4 in Passenger::WatchdogLauncher::start(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Passenger::Json::Value const&, boost::function<void ()> const&) ()
#7  0x000055f0b6286254 in psg_watchdog_launcher_start ()
#8  0x000055f0b6201523 in start_watchdog ()
#9  0x000055f0b62018f3 in init_module ()
#10 0x000055f0b611c022 in ngx_init_modules ()
#11 0x000055f0b611623c in ngx_init_cycle ()
#12 0x000055f0b60f38b0 in main ()
```
